#!/usr/bin/env bash
# update-stream-url.sh — read the current Cloudflare quick-tunnel URL from
# cloudflared.log, patch it into tv-site/index.html, commit, push.
#
# Use after restarting cloudflared (quick tunnels rotate their hostname on
# every restart). Obsolete once a named tunnel + permanent CNAME are in place.
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SITE="$(cd "${HERE}/../tv-site" && pwd)"
LOG="${HERE}/cloudflared.log"
INDEX="${SITE}/index.html"

# Grab the most recent trycloudflare.com URL from the log (tail -1 in case
# cloudflared reconnected and printed multiple URLs across its lifetime).
URL="$(grep -oE 'https://[a-z0-9-]+\.trycloudflare\.com' "${LOG}" | tail -1)"
if [[ -z "${URL}" ]]; then
  echo "FAIL: no trycloudflare.com URL found in ${LOG}" >&2
  exit 1
fi
MANIFEST="${URL}/program/index.m3u8"
echo "current tunnel:  ${URL}"

# Pull the URL currently pinned in index.html (quoted, single line).
CURRENT="$(grep -oE 'https://[a-z0-9-]+\.trycloudflare\.com/program/index\.m3u8' "${INDEX}" | head -1 || true)"
echo "index.html has: ${CURRENT:-<none>}"

if [[ "${CURRENT}" == "${MANIFEST}" ]]; then
  echo "already up to date — nothing to push"
  exit 0
fi

# sed -i '' is the macOS form; Linux would be sed -i.
# Only runs if CURRENT is non-empty — avoids a no-op replace_all.
if [[ -n "${CURRENT}" ]]; then
  sed -i '' "s|${CURRENT}|${MANIFEST}|g" "${INDEX}"
else
  echo "FAIL: no existing trycloudflare URL in index.html to replace" >&2
  exit 1
fi

cd "${SITE}"
git add index.html
git commit -m "Update stream URL after tunnel rotation

Auto-generated by mediamtx/update-stream-url.sh."
git push origin main
echo
echo "pushed. GitHub Pages rebuilds in ~30-60s."
